sudo: false 
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
#    - os: osx
#      osx_image: xcode8

before_script: 
  - java -version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use oraclejdk8; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages.git
  - ughub/ughub install ugcore ConvectionDiffusion LuaShell Neurolucida
  - mkdir build && cd build && cmake ../ -DTARGET=vrl -DLAPACK=OFF -DBLAS=OFF -DDIM="1;2;3" -DCOMPILE_INFO=OFF -DConvectionDiffusion=ON -DLuaShell=ON -DNeurolucida=ON
  - travis_wait 800 make
  - cd ..
  - "export TERM=dumb"
  - travis_wait 640 ./build_vrl_ug_and_api.sh 

script:
  - ./build_vrl_userdata.sh
  - ./build_neurolucida.sh
 
deploy:
  provider: releases
  api_key: "$TRAVIS_ACCESS_TOKEN"
  file: /home/travis/build/NeuroBox3D/VRL-NeuroBox-Plugin/VRL-Neurolucida-Project/build/libs/VRL-Neurolucida-Plugin.jar
  skip_cleanup: true
  on:
    tags: true
