before_script: 
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub install ugcore LuaShell
  - mkdir build && cd build && cmake ../ -DTARGET=vrl -DLAPACK=OFF -DBLAS=OFF -DDIM="1;2;3" -DCOMPILE_INFO=OFF
  - travis_wait 640 make
  - cd ..
  - ./build_vrl_ug.sh 
