sudo: false 
dist: trusty
language: cpp
os: 
  - linux
  - osx

ox_image:
  - xcode8

before_script: 
  - ./check_os.sh && jdk_switcher oraclejdk8
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages.git
  - ughub/ughub install ugcore ConvectionDiffusion LuaShell Neurolucida
  - mkdir build && cd build && cmake ../ -DTARGET=vrl -DLAPACK=OFF -DBLAS=OFF -DDIM="1;2;3" -DCOMPILE_INFO=OFF -DConvectionDiffusion=ON -DLuaShell=ON -DNeurolucida=ON
  - travis_wait 800 make
  - cd ..
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"
  - travis_wait 640 ./build_vrl_ug_and_api.sh 

script:
  - ./build_vrl_userdata.sh
  - ./build_neurolucida.sh
  - ./deploy_neurolucida.sh
 #  - ./build_neurobox.sh
 #  - ./deploy_neurobox.sh
